name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: travel-website
          USERNAME: arshiya-hamdani
        run: |
          npm run build
          git config --global user.name "arshiya-hamdani"
          git config --global user.email "arshiya-hamdani@users.noreply.github.com"
          git remote add origin https://github.com/${USERNAME}/${REPOSITORY_NAME}.git
          git push --force origin main:gh-pages
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages